"""Shared configuration and style constants for revision figures."""

from src.revision.common import (
    ABLATION_REPEATS,
    AUC_REPEATS,
    CACHE_DIR,
    CVAE_EPOCHS,
    DATASET_COLORS,
    DATASET_MARKERS,
    DATASET_ORDER,
    LABEL_RED,
    METHOD_COLORS,
    METHOD_ORDER,
    METHOD_PASTELS,
    METHODS,
    NEUTRAL,
    NOISE_FRAC,
    NOISE_REPEATS,
    PASTEL_CORR_CMAP,
    PROBE_SIGMAS,
    REAL_BLUE,
    REAL_GREY,
    REVISION_RUN_MODE,
    RUN_MODE,
    RUN_PRESETS,
    SEED,
    SYN_RED,
    TSTR_REPEATS,
    repo_root,
)
